
-- /////////////// Create EMPLOYEES Mysql Database //////////////////////

-- //////////// 1. Aggregation Functions //////////////////////

SELECT SUM(COST) FROM PETRESCUE;

SELECT SUM(COST) AS SUM_OF_COST FROM PETRESCUE;

SELECT MAX(QUANTITY) FROM PETRESCUE;

SELECT MIN(QUANTITY) FROM PETRESCUE;

SELECT AVG(COST) FROM PETRESCUE;

-- //////////// 2. Scalar Functions and String Functions //////////////////////

SELECT ROUND(COST) FROM PETRESCUE;

SELECT ROUND(COST, 0) FROM PETRESCUE;

SELECT ROUND(COST, 2) FROM PETRESCUE;

SELECT LENGTH(ANIMAL) FROM PETRESCUE;

SELECT UCASE(ANIMAL) FROM PETRESCUE;

SELECT LCASE(ANIMAL) FROM PETRESCUE;

-- //////////// 3. Data Functions  //////////////////////

SELECT DAY(RESCUEDATE) FROM PETRESCUE;

SELECT MONTH(RESCUEDATE) FROM PETRESCUE;

SELECT YEAR(RESCUEDATE) FROM PETRESCUE;

SELECT DATE_ADD(RESCUEDATE, INTERVAL 3 DAY) FROM PETRESCUE

SELECT DATE_ADD(RESCUEDATE, INTERVAL 2 MONTH) FROM PETRESCUE

SELECT DATE_SUB(RESCUEDATE, INTERVAL 3 DAY) FROM PETRESCUE

SELECT DATEDIFF(CURRENT_DATE, RESCUEDATE) FROM PETRESCUE

SELECT FROM_DAYS(DATEDIFF(CURRENT_DATE, RESCUEDATE)) FROM PETRESCUE

-- //////////// Practice  //////////////////////

SELECT AVG(COST/QUANTITY) FROM PETRESCUE WHERE ANIMAL = 'Dog';

SELECT DISTINCT UCASE(ANIMAL) FROM PETRESCUE;

SELECT * FROM PETRESCUE WHERE LCASE(ANIMAL)="cat";

SELECT SUM(QUANTITY) FROM PETRESCUE WHERE MONTH(RESCUEDATE)="05";

SELECT ID, DATE_ADD(RESCUEDATE, INTERVAL 1 YEAR) FROM PETRESCUE;
